name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
      
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_ADDRESS }} << 'EOF'
            cd /var/www
            git pull origin master

            docker compose up -d

             docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} sh -c 'apt-get update && apt-get install -y netcat'

            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} sh -c 'until nc -z mysql 3306; do sleep 2; done'

            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} composer install --no-interaction --prefer-dist --optimize-autoloader
            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} php artisan migrate --force
            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} php artisan config:cache
            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} php artisan route:cache
            docker exec -i ${{ secrets.VPS_CONTAINER_NAME }} php artisan view:cache
          EOF
